/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Coordinates { 'latitude' : number, 'longitude' : number }
export interface Washroom {
  'features' : WashroomFeatures,
  'name' : string,
  'address' : string,
  'radiusMeters' : number,
  'coordinates' : Coordinates,
}
export interface WashroomFeatures {
  'babyChangingStation' : boolean,
  'wheelchairAccessible' : boolean,
  'accessibleStalls' : boolean,
  'genderNeutral' : boolean,
}
export interface _SERVICE {
  'addWashroom' : ActorMethod<
    [string, string, Coordinates, WashroomFeatures, number],
    undefined
  >,
  'findAccessibleWashrooms' : ActorMethod<[string, number], Array<Washroom>>,
  'findAccessibleWashroomsCoords' : ActorMethod<
    [Coordinates, number],
    Array<Washroom>
  >,
  'findNearestAccessibleWashroom' : ActorMethod<[Coordinates], [] | [Washroom]>,
  'initializeIfEmpty' : ActorMethod<[], undefined>,
  'updateWashroomFeatures' : ActorMethod<[string, WashroomFeatures], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];