/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Coordinates = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const WashroomFeatures = IDL.Record({
  'babyChangingStation' : IDL.Bool,
  'wheelchairAccessible' : IDL.Bool,
  'accessibleStalls' : IDL.Bool,
  'genderNeutral' : IDL.Bool,
});
export const Washroom = IDL.Record({
  'features' : WashroomFeatures,
  'name' : IDL.Text,
  'address' : IDL.Text,
  'radiusMeters' : IDL.Float64,
  'coordinates' : Coordinates,
});

export const idlService = IDL.Service({
  'addWashroom' : IDL.Func(
      [IDL.Text, IDL.Text, Coordinates, WashroomFeatures, IDL.Float64],
      [],
      [],
    ),
  'findAccessibleWashrooms' : IDL.Func(
      [IDL.Text, IDL.Float64],
      [IDL.Vec(Washroom)],
      ['query'],
    ),
  'findAccessibleWashroomsCoords' : IDL.Func(
      [Coordinates, IDL.Float64],
      [IDL.Vec(Washroom)],
      ['query'],
    ),
  'findNearestAccessibleWashroom' : IDL.Func(
      [Coordinates],
      [IDL.Opt(Washroom)],
      ['query'],
    ),
  'initializeIfEmpty' : IDL.Func([], [], []),
  'updateWashroomFeatures' : IDL.Func([IDL.Text, WashroomFeatures], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Coordinates = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const WashroomFeatures = IDL.Record({
    'babyChangingStation' : IDL.Bool,
    'wheelchairAccessible' : IDL.Bool,
    'accessibleStalls' : IDL.Bool,
    'genderNeutral' : IDL.Bool,
  });
  const Washroom = IDL.Record({
    'features' : WashroomFeatures,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'radiusMeters' : IDL.Float64,
    'coordinates' : Coordinates,
  });
  
  return IDL.Service({
    'addWashroom' : IDL.Func(
        [IDL.Text, IDL.Text, Coordinates, WashroomFeatures, IDL.Float64],
        [],
        [],
      ),
    'findAccessibleWashrooms' : IDL.Func(
        [IDL.Text, IDL.Float64],
        [IDL.Vec(Washroom)],
        ['query'],
      ),
    'findAccessibleWashroomsCoords' : IDL.Func(
        [Coordinates, IDL.Float64],
        [IDL.Vec(Washroom)],
        ['query'],
      ),
    'findNearestAccessibleWashroom' : IDL.Func(
        [Coordinates],
        [IDL.Opt(Washroom)],
        ['query'],
      ),
    'initializeIfEmpty' : IDL.Func([], [], []),
    'updateWashroomFeatures' : IDL.Func([IDL.Text, WashroomFeatures], [], []),
  });
};

export const init = ({ IDL }) => { return []; };